package confsources

var CONFIG_SOURCE_PRIORITY_DEFAULT = -999

var CONFIG_SOURCE_PRIORITY_ENV_VAR = 0

var CONFIG_SOURCE_PRIORITY_ENV_VAR_PROPERTIES = 10
var CONFIG_SOURCE_PRIORITY_ENV_VAR_JSON = 20
var CONFIG_SOURCE_PRIORITY_ENV_VAR_YAML = 30
var CONFIG_SOURCE_PRIORITY_ENV_VAR_TOML = 40

var CONFIG_SOURCE_PRIORITY_FILE_PROPERTIES = 50
var CONFIG_SOURCE_PRIORITY_FILE_JSON = 60
var CONFIG_SOURCE_PRIORITY_FILE_YAML = 70
var CONFIG_SOURCE_PRIORITY_FILE_TOML = 80

var CONFIG_SOURCE_PRIORITY_ARGS = 100

var CONFIG_SOURCE_PRIORITY_TESTS = 999
